root: /
permalink: /:year-:month/:title/
highlighter: rouge
paginate: 5

title: Matias Blog
description: "From electrons to ideas: random thoughts about anything computable"
url: https://pmatias.me

plugins: [jekyll-paginate]

talkyard_server_url: https://comments-for-pmatias-me.talkyard.net
